if (!require("plotly")) install.packages("plotly",dependencies = TRUE)
if (!require("shiny")) install.packages("shiny",dependencies = TRUE)
if (!require("shinydashboard")) install.packages("shinydashboard",dependencies = TRUE)
if (!require("zoo")) install.packages("zoo",dependencies = TRUE)
if (!require("RColorBrewer")) install.packages("RColorBrewer",dependencies = TRUE)
if (!require("pracma")) install.packages("pracma",dependencies = TRUE)
if (!require("zeitgebr")) install.packages("zeitgebr",dependencies = TRUE)
